import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { 
  PlusCircle, 
  Library, 
  Layers, 
  GalleryVertical, 
  BarChart3, 
  PieChart, 
  Upload, 
  FileText,
  ChevronRight,
  TrendingUp
} from "lucide-react";
import { useAuth } from "../context/AuthContext";
import "./DashboardPage.css";

const API_URL = process.env.REACT_APP_API_URL || "http://localhost:5000";

const DashboardPage = () => {
  const { user } = useAuth();
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchStats = async () => {
      try {
        const res = await fetch(`${API_URL}/api/flashcards/stats`, {
          credentials: "include",
        });
        if (res.ok) {
          const data = await res.json();
          setStats(data);
        }
      } catch (e) {
        console.error("Failed to fetch stats", e);
      } finally {
        setLoading(false);
      }
    };
    fetchStats();
  }, []);

  if (loading) {
    return (
      <div className="dashboard-page">
        <div className="dashboard-loading">Loading your dashboard...</div>
      </div>
    );
  }

  const greeting = () => {
    const hour = new Date().getHours();
    if (hour < 12) return "Good Morning";
    if (hour < 17) return "Good Afternoon";
    return "Good Evening";
  };

  return (
    <div className="dashboard-page">
      <div className="dashboard-container">
        {/* Header */}
        <div className="dashboard-header">
          <div>
            <h1 className="dashboard-greeting">
              {greeting()}, <span className="dashboard-name">{user?.name || "User"}</span>
            </h1>
            <p className="dashboard-subtitle">Here's your study activity overview.</p>
          </div>
          <div className="dashboard-header-actions">
            <Link to="/input" className="btn btn-primary">
              <Upload size={18} />
              <span>Upload New PDF</span>
            </Link>
          </div>
        </div>

        {/* Stat Cards */}
        <div className="stats-grid">
          <div className="stat-card glass-panel">
            <div className="stat-icon-wrapper blue">
              <Layers size={24} />
            </div>
            <div className="stat-info">
              <span className="stat-label">Total Decks</span>
              <span className="stat-value">{stats?.totalDecks || 0}</span>
              <span className="stat-detail">Documents uploaded</span>
            </div>
          </div>
          <div className="stat-card glass-panel">
            <div className="stat-icon-wrapper purple">
              <GalleryVertical size={24} />
            </div>
            <div className="stat-info">
              <span className="stat-label">Total Flashcards</span>
              <span className="stat-value">{stats?.totalCards || 0}</span>
              <span className="stat-detail">Generated by AI</span>
            </div>
          </div>
          <div className="stat-card glass-panel">
            <div className="stat-icon-wrapper amber">
              <BarChart3 size={24} />
            </div>
            <div className="stat-info">
              <span className="stat-label">Avg Cards / Deck</span>
              <span className="stat-value">
                {stats?.totalDecks > 0
                  ? Math.round(stats.totalCards / stats.totalDecks)
                  : 0}
              </span>
              <span className="stat-detail">Per document</span>
            </div>
          </div>
          <div className="stat-card glass-panel">
            <div className="stat-icon-wrapper emerald">
              <PieChart size={24} />
            </div>
            <div className="stat-info">
              <span className="stat-label">Difficulty Split</span>
              <span className="stat-value stat-value-small">
                {stats?.diffDistribution?.easy || 0}E / {stats?.diffDistribution?.medium || 0}M / {stats?.diffDistribution?.hard || 0}H
              </span>
              <span className="stat-detail">Easy / Medium / Hard</span>
            </div>
          </div>
        </div>

        {/* Middle Row: Marks Distribution + Quick Actions */}
        <div className="dashboard-mid-row">
          {/* Marks Breakdown */}
          <div className="marks-panel glass-panel">
            <div className="panel-header">
              <TrendingUp size={18} className="panel-icon" />
              <h3 className="panel-title">Marks Distribution</h3>
            </div>
            <div className="marks-bars">
              {[1, 2, 5, 10].map((mark) => {
                const count = stats?.markDistribution?.[mark] || 0;
                const maxCount = Math.max(
                  ...Object.values(stats?.markDistribution || { 1: 1 })
                );
                const pct = maxCount > 0 ? (count / maxCount) * 100 : 0;
                const colors = { 1: '#3B82F6', 2: '#10B981', 5: '#F59E0B', 10: '#EF4444' };
                return (
                  <div key={mark} className="mark-row">
                    <span className="mark-label">{mark}M</span>
                    <div className="mark-bar-bg">
                      <div
                        className="mark-bar-fill"
                        style={{ width: `${pct}%`, backgroundColor: colors[mark] }}
                      />
                    </div>
                    <span className="mark-count">{count}</span>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Quick Actions */}
          <div className="actions-panel glass-panel">
            <h3 className="panel-title">Quick Actions</h3>
            <div className="quick-actions-list">
              <Link to="/input" className="quick-action-item">
                <div className="qa-icon-wrapper">
                  <PlusCircle size={20} />
                </div>
                <div>
                  <span className="qa-title">Upload PDF</span>
                  <span className="qa-desc">Generate new flashcards</span>
                </div>
                <ChevronRight size={18} className="qa-arrow" />
              </Link>
              <Link to="/review" className="quick-action-item">
                <div className="qa-icon-wrapper">
                  <Library size={20} />
                </div>
                <div>
                  <span className="qa-title">Library</span>
                  <span className="qa-desc">Browse all your decks</span>
                </div>
                <ChevronRight size={18} className="qa-arrow" />
              </Link>
            </div>
          </div>
        </div>

        {/* Recent Decks */}
        <div className="recent-panel glass-panel">
          <div className="panel-header">
            <FileText size={18} className="panel-icon" />
            <h3 className="panel-title">Recent Uploads</h3>
          </div>
          {stats?.recentDecks?.length > 0 ? (
            <div className="recent-list">
              {stats.recentDecks.map((deck, idx) => (
                <Link to="/review" key={idx} className="recent-item">
                  <div className="recent-info">
                    <span className="recent-name">{deck.filename}</span>
                    <span className="recent-date">
                      {new Date(deck.uploadDate).toLocaleDateString()}
                    </span>
                  </div>
                  <div className="recent-meta">
                    <span className="recent-count">{deck.cardCount} cards</span>
                    <ChevronRight size={16} />
                  </div>
                </Link>
              ))}
            </div>
          ) : (
            <div className="recent-empty">
              <p>No documents uploaded yet.</p>
              <Link to="/input" className="btn btn-secondary">Upload your first PDF</Link>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default DashboardPage;
